name: deepclean-online
channels:
  - conda-forge
dependencies:
  - python=3.8
  - gwpy
  - attrs
  - requests
  - numpy
  - tblib
  - python-ldas-tools-framecpp
  - pip
  - pip:
      - -e ./stillwater
      - git+https://github.com/alecgunny/typeo.git@main
      - --extra-index-url "https://pypi.ngc.nvidia.com"
      - tritonclient[all]
      - wurlitzer
